[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = false
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
evm_version = "cancun"
fuzz = { runs = 1_000 }
via-ir = true
gas_reports = ["*"]
optimizer = true
optimizer_runs = 1_000_000
script = "scripts"
solc_version = "0.8.26" # Adjust to match LayerZero contracts if necessary
test = "test"
cache_path  = "cache_forge"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=lib/forge-std/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "v3-core/=lib/v3-core/",
    "v3-periphery/=lib/v3-periphery/contracts/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/swap-router/=lib/swap-router-contracts/",
    "modulekit/=lib/modulekit/src/",
]
